### ISSUE TITLE
The summary of changes in the Charter says "none" which is ... misleading

### ISSUE THREAD

**Issue by dwsinger** [w3c/audiobooks-wg-charter#6]
as the [diff](https://services.w3.org/htmldiff?doc1=https%3A%2F%2Fwww.w3.org%2F2017%2F04%2Fpubl-wg-charter%2F&doc2=https%3A%2F%2Fwww.w3.org%2F2020%2F09%2Fproposed-audiobooks-wg-charter.html) suggests, this is not the case.

I think the table should include a sentence of summary like this: “Restructured as the successor to the Publishing WG, under a new name, but with the same scope and deliverables; edited for sense and flow..”, or whatever makes a reasonable summary

**Comment by iherman** [comment]
Thanks @dwsinger. I have created the PR #7, will merge it (if it is all right with you) when the vote is over.
